version: '3.7'
services:
  node:
    build: ./gate-simulator
    image: node:1.0
    ports:
      - '9999:9999'

  mysql:
    image: mysql:8.0.34
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
